# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...
    - name: created test certs
      run: |
       mkdir test_data
       openssl req -newkey rsa:2048 -nodes -keyout test_data/testkey.pem -x509 -days 1 -out test_data/testcert.pem -subj "/C=US/ST=state/L=location/O=organization/CN=domain.com"
    
    - name: Test      
      run: go test -race -cover -covermode=atomic -coverprofile=coverage.out -json ./... > test-report.json

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
